
apiVersion: v1
kind: Service
metadata:
  name: forecasting
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: forecasting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecasting
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecasting
  template:
    metadata:
      labels:
        app: forecasting
        {{- include "timeseries.labels" . | nindent 8 }}
    spec:
      {{- if .Values.shared.pvc.enabled }}
      initContainers:
        {{- include "timeseries.shared.initContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: forecasting
          image: {{ .Values.images.forecasting }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: {{ printf "postgresql+psycopg2://%s:%s@processing-timescaledb:5432/timeseries" .Values.postgres.credentials.user .Values.postgres.credentials.password | quote }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_INPUT_TOPIC
              value: {{ .Values.kafkaConfig.forecasting.inputTopic | quote }}
            - name: KAFKA_OUTPUT_TOPIC
              value: {{ .Values.kafkaConfig.forecasting.outputTopic | quote }}
            - name: KAFKA_ERR_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_ERR_TOPIC
            - name: PREPROCESSING_SERVICE_URL
              value: {{ .Values.env.preprocessingServiceUrl | quote }}
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PYTHONUNBUFFERED
            - name: PYTHONPATH
              value: /app
          volumeMounts:
            - name: models
              mountPath: /app/models
            {{- if .Values.shared.pvc.enabled }}
            {{- include "timeseries.shared.volumeMounts" . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 30

      # 🔁 Consolidated volumes (single block)
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: forecasting-models-pvc
        {{- if .Values.shared.pvc.enabled }}
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Values.shared.pvc.name }}
        {{- end }}
