
apiVersion: v1
kind: Service
metadata:
  name: ingestion
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8009
      targetPort: 8009
  selector:
    app: ingestion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
        {{- include "timeseries.labels" . | nindent 8 }}
    spec:
      {{- if .Values.shared.pvc.enabled }}
      initContainers:
{{- include "timeseries.shared.initContainer" . | nindent 8 }}
      volumes:
{{- include "timeseries.shared.volumes" . | nindent 8 }}
      {{- end }}
      containers:
        - name: ingestion
          image: {{ .Values.images.ingestion }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: 8009
          env:
            - name: DATABASE_URL
              value: {{ printf "postgresql+psycopg2://%s:%s@ingestion-timescaledb:5432/timeseries" .Values.postgres.credentials.user .Values.postgres.credentials.password | quote }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_OUTPUT_TOPIC
              value: {{ .Values.kafkaConfig.preprocessing.inputTopic | quote }}
            - name: KAFKA_ERR_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_ERR_TOPIC
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PYTHONUNBUFFERED
          volumeMounts:
            {{- if .Values.shared.pvc.enabled }}
{{- include "timeseries.shared.volumeMounts" . | nindent 12 }}
            {{- end }}
