
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: kafka-service
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        {{- include "timeseries.labels" . | nindent 8 }}
    spec:
      containers:
        - name: kafka
          image: {{ .Values.images.kafka }}
          ports:
            - containerPort: 9092
              name: plaintext
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:{{ .Values.kafka.zookeeper.clientPort }}
            - name: KAFKA_BROKER_ID
              value: "{{ .Values.kafka.brokerId }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-0.kafka-service.{{ .Release.Namespace }}.svc.cluster.local:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "{{ ternary "true" "false" .Values.kafka.autoCreateTopics }}"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "{{ .Values.kafka.retentionHours }}"
            - name: KAFKA_NUM_PARTITIONS
              value: "{{ .Values.kafka.numPartitions }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
          readinessProbe:
            exec:
              command: ["sh", "-c", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
