
apiVersion: v1
kind: Service
metadata:
  name: processing-timescaledb
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
  selector:
    app: processing-timescaledb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: processing-timescaledb
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  serviceName: processing-timescaledb
  replicas: 1
  selector:
    matchLabels:
      app: processing-timescaledb
  template:
    metadata:
      labels:
        app: processing-timescaledb
        {{- include "timeseries.labels" . | nindent 8 }}
    spec:
      containers:
        - name: timescaledb
          image: {{ .Values.images.timescaledb }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.timescaledb.processing.db | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.credentials.user }}", "-d", "{{ .Values.timescaledb.processing.db }}"]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.credentials.user }}", "-d", "{{ .Values.timescaledb.processing.db }}"]
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: timescaledb-data-pvc
        - name: init-scripts
          configMap:
            name: timescaledb-init-scripts
