
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.credentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
