
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.kafka.zookeeper.clientPort }}
      name: client
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  serviceName: zookeeper-service
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        {{- include "timeseries.labels" . | nindent 8 }}
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.images.zookeeper }}
          ports:
            - containerPort: {{ .Values.kafka.zookeeper.clientPort }}
              name: client
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.kafka.zookeeper.clientPort }}"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          livenessProbe:
            tcpSocket:
              port: {{ .Values.kafka.zookeeper.clientPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: {{ .Values.kafka.zookeeper.clientPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
