apiVersion: v1
kind: Service
metadata:
  name: ingestion-timescaledb
  namespace: timeseries
spec:
  ports:
    - port: 5432
  selector:
    app: ingestion-timescaledb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ingestion-timescaledb
  namespace: timeseries
spec:
  serviceName: ingestion-timescaledb
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-timescaledb
  template:
    metadata:
      labels:
        app: ingestion-timescaledb
    spec:
      containers:
      - name: timescaledb
        image: timescale/timescaledb:latest-pg15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "timeseries"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - tsuser
            - -d
            - timeseries
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - tsuser
            - -d
            - timeseries
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ingestion-data-pvc
      - name: init-scripts
        configMap:
          name: ingestion-init-scripts