apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: timeseries
spec:
  clusterIP: None  # This makes it a headless service
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
