apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-data-pvc
  namespace: timeseries
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingestion-data-pvc
  namespace: timeseries
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pipeline-data-pvc
  namespace: timeseries
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forecasting-models-pvc
  namespace: timeseries
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi