apiVersion: v1
kind: Pod
metadata:
  name: test-forecasting
  namespace: timeseries
spec:
  containers:
  - name: forecasting
    image: deployment_forecasting:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8001